# AArch64 cross-compiler toolchain for RK3566 Linux
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TOOLCHAIN aarch64-linux-gnu-)

set(CMAKE_C_COMPILER    ${TOOLCHAIN}gcc)
set(CMAKE_CXX_COMPILER  ${TOOLCHAIN}g++)
set(CMAKE_AR            ${TOOLCHAIN}ar)
set(CMAKE_OBJCOPY       ${TOOLCHAIN}objcopy)
set(CMAKE_OBJDUMP       ${TOOLCHAIN}objdump)
set(CMAKE_SIZE          ${TOOLCHAIN}size)
set(CMAKE_RANLIB        ${TOOLCHAIN}ranlib)
set(CMAKE_STRIP         ${TOOLCHAIN}strip)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
