# ARM GCC toolchain for STM32H747 (Cortex-M7/M4)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN arm-none-eabi-)

set(CMAKE_C_COMPILER    ${TOOLCHAIN}gcc)
set(CMAKE_CXX_COMPILER  ${TOOLCHAIN}g++)
set(CMAKE_ASM_COMPILER  ${TOOLCHAIN}gcc)
set(CMAKE_AR            ${TOOLCHAIN}ar)
set(CMAKE_OBJCOPY       ${TOOLCHAIN}objcopy)
set(CMAKE_OBJDUMP       ${TOOLCHAIN}objdump)
set(CMAKE_SIZE          ${TOOLCHAIN}size)
set(CMAKE_RANLIB        ${TOOLCHAIN}ranlib)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
